### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by soumyakantiroychowdhury**
Mismatch with class 'Put' in core-domin/.../domain/meta/Put.java

Signed-off-by: soumyakantiroychowdhury <soumyakanti.roychowdhury@gmail.com>

### CODE REVIEW

**Comment by JPWKU** [comment]
recheck

**Comment by soumyakantiroychowdhury** [comment]
@JPWKU Please clarify what to 'recheck'. I think it is a simple typo in the code that @jpwhitemn approved.

**Comment by trcox** [comment]
Soumya, your pull requests are failing our commit signing check (DCO) because your git user name parameter in your local environment does not match your global git user name configuration (expecting 'soumyakantiroychowdhury'). If you can fix that and update the commits then we will get your changes merged!

Recheck is an automated build hook for our verify jobs to rerun, Jeremy was checking to see if the build error was a temporary event.

Thanks for your contributions!

**Comment by soumyakantiroychowdhury** [comment]
Thanks @trcox - I am sorry that I am not that comfortable with git. I updated the commit message after some effort. Please let me know if it is OK, else if I have messed up the things - I can close this PR and create a new one.

**Comment by trcox** [comment]
recheck

**Pull request merged**
