### PR TITLE
Addressing RAML discrepancies, removing bool return types

### PR DESCRIPTION
**Pull request by tsconn23**
Please refer to https://github.com/edgexfoundry/edgex-go/issues/211

Signed-off-by: Trevor Conn <trevor_conn@dell.com>

### CODE REVIEW

**Comment by tsconn23** [comment]
From Docker-Verify logs "Build step 'Execute shell' marked build as failure"

**Comment by tsconn23** [comment]
recheck

**Comment by jpwhitemn** [comment]
@JPWKU - can you assist?  Looks like recheck did not work.

**Comment by tsconn23** [comment]
recheck

**Pull request merged**
